//------------------------------------------------------------------------------
// <auto-generated>
//     Denna kod har genererats av ett verktyg.
//     Körtidsversion:4.0.30319.42000
//
//     Ändringar i denna fil kan orsaka fel och kommer att förloras om
//     koden återgenereras.
// </auto-generated>
//------------------------------------------------------------------------------



[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(Namespace="WCF_Service_Days", ConfigurationName="IDays")]
public interface IDays
{
    
    [System.ServiceModel.OperationContractAttribute(Action="WCF_Service_Days/IDays/DaysOld", ReplyAction="WCF_Service_Days/IDays/DaysOldResponse")]
    double DaysOld(int year, int month, int day);
    
    [System.ServiceModel.OperationContractAttribute(Action="WCF_Service_Days/IDays/DaysOld", ReplyAction="WCF_Service_Days/IDays/DaysOldResponse")]
    System.Threading.Tasks.Task<double> DaysOldAsync(int year, int month, int day);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface IDaysChannel : IDays, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class DaysClient : System.ServiceModel.ClientBase<IDays>, IDays
{
    
    public DaysClient()
    {
    }
    
    public DaysClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public DaysClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public DaysClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public DaysClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public double DaysOld(int year, int month, int day)
    {
        return base.Channel.DaysOld(year, month, day);
    }
    
    public System.Threading.Tasks.Task<double> DaysOldAsync(int year, int month, int day)
    {
        return base.Channel.DaysOldAsync(year, month, day);
    }
}
