//------------------------------------------------------------------------------
// <auto-generated>
//     Denna kod har genererats av ett verktyg.
//     Körtidsversion:4.0.30319.42000
//
//     Ändringar i denna fil kan orsaka fel och kommer att förloras om
//     koden återgenereras.
// </auto-generated>
//------------------------------------------------------------------------------



[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(Namespace="WCF_Service_Hobby", ConfigurationName="IHobby")]
public interface IHobby
{
    
    [System.ServiceModel.OperationContractAttribute(Action="WCF_Service_Hobby/IHobby/WorstMovieTitle", ReplyAction="WCF_Service_Hobby/IHobby/WorstMovieTitleResponse")]
    string WorstMovieTitle(string year);
    
    [System.ServiceModel.OperationContractAttribute(Action="WCF_Service_Hobby/IHobby/WorstMovieTitle", ReplyAction="WCF_Service_Hobby/IHobby/WorstMovieTitleResponse")]
    System.Threading.Tasks.Task<string> WorstMovieTitleAsync(string year);
    
    [System.ServiceModel.OperationContractAttribute(Action="WCF_Service_Hobby/IHobby/YearOfMovie", ReplyAction="WCF_Service_Hobby/IHobby/YearOfMovieResponse")]
    string YearOfMovie(string movieTitle);
    
    [System.ServiceModel.OperationContractAttribute(Action="WCF_Service_Hobby/IHobby/YearOfMovie", ReplyAction="WCF_Service_Hobby/IHobby/YearOfMovieResponse")]
    System.Threading.Tasks.Task<string> YearOfMovieAsync(string movieTitle);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface IHobbyChannel : IHobby, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class HobbyClient : System.ServiceModel.ClientBase<IHobby>, IHobby
{
    
    public HobbyClient()
    {
    }
    
    public HobbyClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public HobbyClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public HobbyClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public HobbyClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public string WorstMovieTitle(string year)
    {
        return base.Channel.WorstMovieTitle(year);
    }
    
    public System.Threading.Tasks.Task<string> WorstMovieTitleAsync(string year)
    {
        return base.Channel.WorstMovieTitleAsync(year);
    }
    
    public string YearOfMovie(string movieTitle)
    {
        return base.Channel.YearOfMovie(movieTitle);
    }
    
    public System.Threading.Tasks.Task<string> YearOfMovieAsync(string movieTitle)
    {
        return base.Channel.YearOfMovieAsync(movieTitle);
    }
}
